// Rules data access. Rules belong to behaviors; confidence drives visibility.
// SCHEMA: rules with confidence < 0.5 are under_review → not returned until confirmed.
import { randomUUID } from "node:crypto";
import type { Database } from "better-sqlite3";

// Rules below this confidence are under_review (hidden from MCP consumers).
export const UNDER_REVIEW_BELOW = 0.5;

// Lifecycle of a rule. 'active' = live; 'superseded' = retired by QA (e.g. a
// duplicate replaced by a canonical one) — hidden from every read. Distinct
// from confidence, which is the strength of the inference.
export type RuleStatus = "active" | "superseded";

export interface Rule {
  id: string;
  behavior_id: string;
  rule_text: string;
  confidence: number;
  source_excerpt: string | null;
  source_id: string | null;
  qa_override: boolean;
  override_reason: string | null;
  status: RuleStatus;
  created_at: string;
  updated_at: string;
}

interface RuleRow {
  id: string;
  behavior_id: string;
  rule_text: string;
  confidence: number;
  source_excerpt: string | null;
  source_id: string | null;
  qa_override: number;
  override_reason: string | null;
  status: string;
  created_at: string;
  updated_at: string;
}

function hydrate(row: RuleRow): Rule {
  return {
    id: row.id,
    behavior_id: row.behavior_id,
    rule_text: row.rule_text,
    confidence: row.confidence,
    source_excerpt: row.source_excerpt,
    source_id: row.source_id,
    qa_override: row.qa_override === 1,
    override_reason: row.override_reason,
    status: row.status as RuleStatus,
    created_at: row.created_at,
    updated_at: row.updated_at,
  };
}

export interface NewRule {
  id?: string; // pre-generated by caller when embedding must precede insert
  behavior_id: string;
  rule_text: string;
  confidence?: number;
  source_excerpt?: string | null;
  source_id?: string | null;
  qa_override?: boolean;
  override_reason?: string | null;
}

// Inserts a rule, returns its id. Used by seeding + tests.
export function insertRule(
  db: Database,
  r: NewRule,
  now: string = new Date().toISOString(),
): string {
  const id = r.id ?? randomUUID();
  db.prepare(
    `INSERT INTO rules
       (id, behavior_id, rule_text, confidence, source_excerpt, source_id,
        qa_override, override_reason, created_at, updated_at)
     VALUES (@id, @behavior_id, @rule_text, @confidence, @source_excerpt, @source_id,
             @qa_override, @override_reason, @created_at, @updated_at)`,
  ).run({
    id,
    behavior_id: r.behavior_id,
    rule_text: r.rule_text,
    confidence: r.confidence ?? 0.7,
    source_excerpt: r.source_excerpt ?? null,
    source_id: r.source_id ?? null,
    qa_override: r.qa_override ? 1 : 0,
    override_reason: r.override_reason ?? null,
    created_at: now,
    updated_at: now,
  });
  return id;
}

// Returns visible rules (confidence >= 0.5) for the given behaviors.
// QA overrides first, then higher confidence. Empty input → empty result.
export function listRulesForBehaviors(
  db: Database,
  behaviorIds: string[],
): Rule[] {
  if (behaviorIds.length === 0) return [];
  const placeholders = behaviorIds.map(() => "?").join(", ");
  const rows = db
    .prepare(
      `SELECT * FROM rules
       WHERE behavior_id IN (${placeholders}) AND confidence >= ? AND status = 'active'
       ORDER BY qa_override DESC, confidence DESC, created_at DESC`,
    )
    .all(...behaviorIds, UNDER_REVIEW_BELOW) as RuleRow[];
  return rows.map(hydrate);
}

// A rule awaiting QA confirmation, paired with its behavior's context so the
// reviewer (memory-keeper) can judge it without a second lookup.
export interface PendingRule {
  rule: Rule;
  behavior_name: string;
  behavior_criticality: string;
  under_review: boolean; // confidence < UNDER_REVIEW_BELOW (hidden from normal MCP reads)
}

// Rules the QA never confirmed (qa_override = 0) — the promotion queue the
// memory-keeper curates. INCLUDES under_review rules (confidence < 0.5), which
// are invisible to every other MCP read: this is the one surface that can
// rescue or discard a weak inference. Excludes deprecated behaviors. Weakest
// confidence first (most in need of a human call), then oldest.
export function listUnconfirmedRules(db: Database): PendingRule[] {
  const rows = db
    .prepare(
      `SELECT r.*, b.name AS behavior_name, b.criticality AS behavior_criticality
         FROM rules r
         JOIN behaviors b ON b.id = r.behavior_id
        WHERE r.qa_override = 0 AND r.status = 'active' AND b.status != 'deprecated'
        ORDER BY r.confidence ASC, r.created_at ASC`,
    )
    .all() as (RuleRow & { behavior_name: string; behavior_criticality: string })[];
  return rows.map((row) => {
    const { behavior_name, behavior_criticality, ...ruleRow } = row;
    return {
      rule: hydrate(ruleRow),
      behavior_name,
      behavior_criticality,
      under_review: ruleRow.confidence < UNDER_REVIEW_BELOW,
    };
  });
}

// A rule inside a duplicate cluster, with its behavior name for display.
export interface DuplicateRule {
  rule: Rule;
  behavior_name: string;
}

// Default token-overlap threshold above which two rules are "near-duplicates".
export const DEFAULT_DUP_THRESHOLD = 0.7;

// Language-agnostic normalization (PT/EN): lowercase, non-alphanumeric → space,
// collapse + trim. Unicode-aware so accented chars survive.
export function normalizeRuleText(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim()
    .replace(/\s+/g, " ");
}

function tokenSet(s: string): Set<string> {
  return new Set(normalizeRuleText(s).split(" ").filter(Boolean));
}

// Jaccard overlap of two token sets. Two empty sets count as identical.
function jaccard(a: Set<string>, b: Set<string>): number {
  if (a.size === 0 && b.size === 0) return 1;
  let inter = 0;
  for (const t of a) if (b.has(t)) inter++;
  const union = a.size + b.size - inter;
  return union === 0 ? 0 : inter / union;
}

// Finds clusters of duplicate / near-duplicate rules across all non-deprecated
// behaviors — the memory-keeper's dedup signal. Two rules join a cluster when
// their normalized text is identical OR their token-overlap (Jaccard) >=
// threshold. Detection only: it never merges or deletes (the keeper proposes,
// the user decides). Clusters of size >= 2 only, largest first; INCLUDES
// under_review and cross-behavior pairs (a duplicate can hide anywhere).
export function findDuplicateRules(
  db: Database,
  threshold: number = DEFAULT_DUP_THRESHOLD,
): DuplicateRule[][] {
  const rows = db
    .prepare(
      `SELECT r.*, b.name AS behavior_name
         FROM rules r
         JOIN behaviors b ON b.id = r.behavior_id
        WHERE r.status = 'active' AND b.status != 'deprecated'
        ORDER BY r.created_at ASC`,
    )
    .all() as (RuleRow & { behavior_name: string })[];

  const items = rows.map((row) => {
    const { behavior_name, ...ruleRow } = row;
    return { rule: hydrate(ruleRow), behavior_name, tokens: tokenSet(ruleRow.rule_text) };
  });

  // Union-find over rule indices.
  const parent = items.map((_, i) => i);
  const find = (x: number): number => {
    while (parent[x] !== x) {
      parent[x] = parent[parent[x]!]!;
      x = parent[x]!;
    }
    return x;
  };
  const union = (a: number, b: number) => {
    parent[find(a)] = find(b);
  };

  for (let i = 0; i < items.length; i++) {
    for (let j = i + 1; j < items.length; j++) {
      if (jaccard(items[i]!.tokens, items[j]!.tokens) >= threshold) union(i, j);
    }
  }

  const groups = new Map<number, DuplicateRule[]>();
  items.forEach((it, i) => {
    const root = find(i);
    if (!groups.has(root)) groups.set(root, []);
    groups.get(root)!.push({ rule: it.rule, behavior_name: it.behavior_name });
  });

  return [...groups.values()].filter((g) => g.length >= 2).sort((a, b) => b.length - a.length);
}

// Active rules that have a stored embedding, paired with the latest vector BLOB.
// Feeds rule-level semantic ranking in search.ts so a query matching rule content
// surfaces the parent behavior even when the behavior name/description doesn't match.
export function listRuleEmbeddings(
  db: Database,
): { rule_id: string; behavior_id: string; vector: Buffer }[] {
  return db
    .prepare(
      `SELECT r.id AS rule_id, r.behavior_id, e.vector
         FROM rules r
         JOIN embeddings e ON e.entity_type = 'rule' AND e.entity_id = r.id
        WHERE r.status = 'active'
        GROUP BY r.id
       HAVING e.created_at = MAX(e.created_at)`,
    )
    .all() as { rule_id: string; behavior_id: string; vector: Buffer }[];
}

export function getRuleById(db: Database, id: string): Rule | null {
  const row = db.prepare("SELECT * FROM rules WHERE id = ?").get(id) as
    | RuleRow
    | undefined;
  return row ? hydrate(row) : null;
}

// QA override: pins a rule as authoritative (confidence 1.0, qa_override=1)
// with a reason. Returns the updated rule, or null if the id is unknown.
export function overrideRule(
  db: Database,
  id: string,
  rule_text: string,
  reason: string,
  now: string = new Date().toISOString(),
): Rule | null {
  const res = db
    .prepare(
      `UPDATE rules
         SET rule_text = @rule_text, confidence = 1.0, qa_override = 1,
             override_reason = @reason, updated_at = @now
       WHERE id = @id`,
    )
    .run({ id, rule_text, reason, now });
  if (res.changes === 0) return null;
  return getRuleById(db, id);
}

// Retires a rule (status='superseded') — e.g. a duplicate the keeper replaced
// with a canonical one. The rule drops out of every read; the reason is kept in
// override_reason as the audit trail of the last QA action. Returns the updated
// rule, or null if the id is unknown. Mirrors overrideRule.
export function retireRule(
  db: Database,
  id: string,
  reason: string,
  now: string = new Date().toISOString(),
): Rule | null {
  const res = db
    .prepare(
      `UPDATE rules
         SET status = 'superseded', override_reason = @reason, updated_at = @now
       WHERE id = @id`,
    )
    .run({ id, reason, now });
  if (res.changes === 0) return null;
  return getRuleById(db, id);
}
