"""
ingest_pdf.py — Fallback ingestion when qa-memory MCP has no LLM key.

Modes:
  1. Auto (ANTHROPIC_API_KEY set):
       python ingest_pdf.py arquivo.pdf
     Reads PDF → calls Claude to extract behaviors/rules → inserts into SQLite.

  2. Manual (no key — Claude-in-chat drives):
       python ingest_pdf.py arquivo.pdf --dry-run
     Reads PDF → prints extracted text for Claude to read.

       python ingest_pdf.py --ingest data.json
     Inserts pre-structured JSON (generated by Claude in chat) into SQLite.

JSON schema (--ingest):
  {
    "source_ref": "ONM-1234",
    "label": "Short description",
    "behaviors": [
      {
        "slug": "unique-kebab-id",
        "name": "Human name",
        "description": "What this behavior does",
        "criticality": "P0|P1|P2|P3",
        "rules": [
          {
            "rule_text": "The rule in plain language.",
            "confidence": 1.0,
            "qa_override": true
          }
        ]
      }
    ]
  }
"""

import argparse
import json
import os
import sqlite3
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def _db_path() -> str:
    env = os.environ.get("QA_MEMORY_DB")
    if env:
        return env
    default = Path(__file__).parent.parent / "QA-memory" / ".qa-memory" / "qa-memory.db"
    return str(default)


# ---------------------------------------------------------------------------
# PDF extraction
# ---------------------------------------------------------------------------

def extract_pdf_text(pdf_path: str) -> str:
    try:
        import fitz  # pymupdf
    except ImportError:
        sys.exit("pymupdf not installed. Run: pip install pymupdf")
    doc = fitz.open(pdf_path)
    pages = [page.get_text() for page in doc]
    doc.close()
    return "\n\n".join(pages)


# ---------------------------------------------------------------------------
# Auto mode: Claude API extraction
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
Extract QA knowledge from the text. Return ONLY valid JSON matching this schema:
{
  "source_ref": "<ticket key or doc title>",
  "label": "<short label>",
  "behaviors": [
    {
      "slug": "<kebab-case unique id>",
      "name": "<behavior name>",
      "description": "<what this area does>",
      "criticality": "P0|P1|P2|P3",
      "rules": [
        {
          "rule_text": "<rule in plain language>",
          "confidence": 0.9,
          "qa_override": true
        }
      ]
    }
  ]
}
Criticality: P0=financial/security, P1=main flow, P2=secondary, P3=cosmetic.
confidence: 1.0 for confirmed behavior, 0.7 for safe inference.
qa_override: true when rule is explicitly stated in source.
No markdown. No commentary. Raw JSON only."""


def extract_with_claude(text: str, source_ref: str) -> dict:
    try:
        import anthropic
    except ImportError:
        sys.exit("anthropic SDK not installed. Run: pip install anthropic")

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        sys.exit("ANTHROPIC_API_KEY not set. Use --dry-run or --ingest mode.")

    client = anthropic.Anthropic(api_key=api_key)
    msg = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": f"source_ref: {source_ref}\n\n{text[:12000]}"}],
    )
    raw = msg.content[0].text.strip()
    return json.loads(raw)


# ---------------------------------------------------------------------------
# SQLite insertion
# ---------------------------------------------------------------------------

def insert_data(data: dict, db_path: str) -> None:
    now = datetime.now(timezone.utc).isoformat()
    conn = sqlite3.connect(db_path)

    source_id = str(uuid.uuid4())
    conn.execute(
        "INSERT INTO sources (id, type, label, source_ref, last_synced, sync_status, checksum, created_at, updated_at)"
        " VALUES (?,?,?,?,?,?,?,?,?)",
        (source_id, "jira", data["label"], data["source_ref"], now, "success",
         f"ingest-{data['source_ref']}-{now[:10]}", now, now),
    )

    behavior_count = 0
    rule_count = 0

    for b in data["behaviors"]:
        bid = str(uuid.uuid4())
        conn.execute(
            "INSERT INTO behaviors (id, name, description, criticality, status, source_ids, confirmed_by_qa, created_at, updated_at)"
            " VALUES (?,?,?,?,?,?,?,?,?)",
            (bid, b["name"], b["description"], b["criticality"], "active",
             json.dumps([source_id]), 1, now, now),
        )
        behavior_count += 1

        for r in b.get("rules", []):
            rid = str(uuid.uuid4())
            conn.execute(
                "INSERT INTO rules (id, behavior_id, rule_text, confidence, source_id, qa_override, created_at, updated_at, status)"
                " VALUES (?,?,?,?,?,?,?,?,?)",
                (rid, bid, r["rule_text"], r.get("confidence", 0.9),
                 source_id, 1 if r.get("qa_override", False) else 0, now, now, "active"),
            )
            rule_count += 1

    conn.commit()
    conn.close()
    print(f"OK — source={source_id}")
    print(f"Behaviors: {behavior_count} | Rules: {rule_count}")
    print(f"DB: {db_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Ingest PDF into qa-memory SQLite.")
    parser.add_argument("pdf", nargs="?", help="Path to PDF file")
    parser.add_argument("--ingest", metavar="JSON_FILE",
                        help="Insert pre-structured JSON (Claude-in-chat mode)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print extracted PDF text only (for Claude to read)")
    parser.add_argument("--db", default=_db_path(), help="SQLite DB path (overrides QA_MEMORY_DB)")
    args = parser.parse_args()

    # Mode 1: --ingest JSON_FILE
    if args.ingest:
        with open(args.ingest, encoding="utf-8") as f:
            data = json.load(f)
        insert_data(data, args.db)
        return

    if not args.pdf:
        parser.print_help()
        sys.exit(1)

    text = extract_pdf_text(args.pdf)

    # Mode 2: --dry-run (print text for Claude in chat)
    if args.dry_run:
        print(text)
        return

    # Mode 3: auto with Claude API
    source_ref = Path(args.pdf).stem
    data = extract_with_claude(text, source_ref)
    insert_data(data, args.db)


if __name__ == "__main__":
    main()
